### ISSUE TITLE
Incorrect I2C Value on MIPS

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_Python_PureIO#17]
I was testing out I2C on MIPS and though it appears to work, I compared the value I was expecting and it appears to be incorrect. This doesn't surprise me as I had to make some slight adjustments for MIPS on SPI and will probably have to apply similar adjustments to I2C.

**Comment by makermelissa** [comment]
I tried a different sensor and am getting correct values, so this is not an issue with PureIO. Closing.

**Comment by makermelissa** [comment]
I'm not sure what changed, but I'm getting the correct value from the original sensor I was having issues with now.

**Comment by ladyada** [comment]
lol
