### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by joachimlindborg** [adafruit/Adafruit_Python_PureIO#2]
Would be nice to have an update on the plans for this project. Will it continue to be developed and have just stalled or is it obsolete due to other implementations? If so which ones? 
I see this implementation is an asset towards other plattforms for example the [onion.io](onion.io)

**Comment by ladyada** [comment]
oops wasnt watching this repo - we're developing it still and will use it as the basis for our circuitpython support layer. any testing you could do would be awesome :)
