### ISSUE TITLE
Error detection via number of bytes read?

### ISSUE THREAD

**Issue by ebradbury** [adafruit/Adafruit_Python_PureIO#24]
Thanks for this great library, I'm using it for on a multi-drop communications bus.

I occasionally request a number of bytes via `read_bytes` which come back all 0xFF. This is likely a hardware issue (pull up? clock stretch?) but I'm wondering if it's possible that Python is erroneously returning a "blank" buffer or buffer full of noise when it should have returned a truncated one due to some lower-level io error.

It seems like the low-level `read` implementations in FileIO handle resizing when fewer than requested bytes are received but I thought I'd ask if there was any way to leverage requested vs received bytes for error detection.

Thanks again

```
>>> b = smbus.SMBus(1)
>>> help(b._device.read)

read(size=-1, /) method of _io.FileIO instance
    Read at most size bytes, returned as bytes.

    Only makes one system call, so less data may be returned than requested.
    In non-blocking mode, returns None if no data is available.
    Return an empty bytes object at EOF.
```

https://github.com/python/cpython/blob/main/Modules/_io/fileio.c#L827

**Comment by ladyada** [comment]
i *believe* in linux if you request data from a i2c peripheral and its NAK'd you will get an IOError exception you need to catch. so in those cases you'd just read a byte at a time. the only way to really know whats up is to get a logic analyzer trace... i2c is one of those "standards thats totally a standard until it isnt and then everything is a mess"

**Comment by ebradbury** [comment]
Thanks for your comment, ladyada. I'd say it's time to invest in an analyzer.
