### ISSUE TITLE
travis pypi

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_Python_PureIO#3]
hey @tannewt as you're doing travis/pypi-fication can you also hit this one? its already in pypi and im doing updates to the code as i Discover New Exciting Things about linux i2c - having it auto update would be glorious

**Comment by makermelissa** [comment]
I ran into this as well. I had to manually update the version number in setup.py. Perhaps adapting the setup script from Adafruit_Python_PlatformDetect would be the easiest way to fix this.

**Comment by makermelissa** [comment]
I'm going to grab this because this falls more into my scope.

**Comment by makermelissa** [comment]
Fixed!
