### ISSUE TITLE
remote IO error

### ISSUE THREAD

**Issue by NikulausRui** [adafruit/Adafruit_Python_PureIO#7]
Thank you for opening an issue on an Adafruit Python library repository.  To
improve the speed of resolution please review the following guidelines and
common troubleshooting steps below before creating the issue:

When I run my program,Such a mistake has occurred.
 File "/home/pi/env/lib/python3.5/site-packages/Adafruit_PureIO/smbus.py", line 256, in write_byte_data
    self._device.write(data)
OSError: [Errno 121] Remote I/O error

The same error occurred in running the test code.
I searched a lot of such questions in Google, but they didn't solve them.
Can you give me some help?

**Comment by ladyada** [comment]
probably a wiring issue, please contact the vendor you bought your sensor device :)
